import { SxProps, Theme } from "@mui/material";

export const CustomGlobalStyle: Record<string, SxProps<Theme> | undefined> = {
  text15white: {
    color: "#FFF",
    fontFamily: "Inter",
    fontSize: "15px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text15bluelight: {
    color: "#44546f",
    fontFamily: "Inter",
    fontSize: "15px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text25black: {
    fontFamily: "Inter",
    fontSize: "25px",
    fontWeight: 700,
    lineHeight: "24px",
    color: "#363737",
  },

  text15gray: {
    fontFamily: "Inter",
    fontSize: "15px",
    fontWeight: 600,
    lineHeight: "24px",
    color: "#C7C7C7",
  },
  text18gray: {
    fontFamily: "Inter",
    fontSize: "18px",
    fontWeight: 600,
    lineHeight: "24px",
    color: "#242424",
  },
  text9gray: {
    fontFamily: "Inter",
    fontSize: "9px",
    fontWeight: 600,
    lineHeight: "24px",
    color: "#C7C7C7",
  },
  text12sublet: {
    color: "#8690A2",
    fontFamily: "Inter",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text20black600: {
    color: "#172B4D",
    fontFamily: "Inter",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  text16black600: {
    color: "#172B4D",
    fontFamily: "Inter",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  text12black600: {
    color: "#172B4D",
    fontFamily: "Inter",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  text14black: {
    color: "#172B4D",
    fontFamily: "Inter",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text12sublet100: {
    color: "#172B4D",
    fontFamily: "Inter",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 100,
    lineHeight: "normal",
  },
  text12blue: {
    color: "#0C66E4",
    fontFamily: "Inter",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 100,
    lineHeight: "normal",
  },
  text14blue: {
    color: "#0C66E4",
    fontFamily: "Inter",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text20sublet: {
    color: "#172B4D",
    fontFamily: "Inter",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  text10: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text50: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "50px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text20: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text20bold: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "normal",
  },
  text15: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "15px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text15bold: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "15px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "normal",
  },
  text13: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text13bold: {
    color: "#325381",
    fontFamily: "Inter",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "normal",
  },
  text13blue: {
    color: "#00C2FF",
    fontFamily: "Inter",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text10red: {
    color: "rgba(222, 6, 6, 0.80)",
    fontFamily: "Inter",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text13red: {
    color: "rgba(222, 6, 6, 0.80)",
    fontFamily: "Inter",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text15bluegray: {
    color: "#c0bfbb",
    fontFamily: "Inter",
    fontSize: "15px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text13bluegray: {
    color: "#6F7B90",
    fontFamily: "Inter",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 200,
    lineHeight: "16px",
  },
  text10bluegray: {
    color: "#6F7B90",
    fontFamily: "Inter",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "16px",
  },
  text14white: {
    color: "white",
    fontFamily: "Inter",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text14bluegray: {
    color: "#6F7B90",
    fontFamily: "Inter",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  text13bluegraybold: {
    color: "#c0bfbb",
    fontFamily: "Inter",
    fontSize: "13px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "normal",
  },
  text12gray: {
    color: "#626f86",
    fontFamily: "Inter",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  text16gray: {
    color: "#626f86",
    fontFamily: "Inter",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
};
