
import './globals.css'
import { ThemeRegistry } from '@/components/Theme/ThemRegistry/ThemeRegistry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { Provider } from './provider'
import Navbar from '@/components/appbar'
import { useRouter } from 'next/router'
import { ReduxProvider } from 'src/redux/provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode, modal: React.ReactNode }) {

  return (
    <ReduxProvider>
      {/* <Provider> */}
      <html lang="en">
        <ThemeRegistry>

          <body >
            {props.children}
            {props.modal}
          </body>
        </ThemeRegistry>
      </html>
      {/* </Provider> */}
    </ReduxProvider>
  )
}
